### PR TITLE
enh: extract fiq/piq

### PR DESCRIPTION
**Pull request by satra**
@jbpoline - updated query

### CODE REVIEW

**Comment by jbpoline** [comment]
thanks a lot - will try asap

**Comment by jbpoline** [comment]
@satra  : hum, seems that this query does not give me any results ... I tried to add the ?piq ?fiq at the end of the select but (as expected) this is not the issue 
does it return results for you ? 

prefix GrayMatter: <http://uri.interlex.org/ilx_0104768#>
prefix afni: <http://purl.org/nidash/afni#>
prefix ants: <http://stnava.github.io/ANTs/>
prefix bids: <http://bids.neuroimaging.io/>
prefix birnlex: <http://bioontology.org/projects/ontologies/birnlex/>
prefix crypto: <http://id.loc.gov/vocabulary/preservation/cryptographicHashFunctions#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dcat: <http://www.w3.org/ns/dcat#>
prefix dct: <http://purl.org/dc/terms/>
prefix dctypes: <http://purl.org/dc/dcmitype/>
prefix dicom: <http://neurolex.org/wiki/Category:DICOM_term/>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix freesurfer: <https://surfer.nmr.mgh.harvard.edu/>
prefix fsl: <http://purl.org/nidash/fsl#>
prefix full4_iq: <https://github.com/dbkeator/nidm-local-terms/issues/2>
prefix hasDatumType: <http://uri.interlex.org/ilx_0738262#>
prefix hasLaterality: <http://uri.interlex.org/ilx_0381387#>
prefix hasMeasurementType: <http://uri.interlex.org/ilx_0381388#>
prefix isAbout: <http://uri.interlex.org/ilx_0381385#>
prefix isMeasureOf: <http://uri.interlex.org/ilx_0381389#>
prefix measurement_datum: <http://uri.interlex.org/base/ilx_0738269#>
prefix ncicb: <http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#>
prefix ncit: <http://ncitt.ncit.nih.gov/>
prefix ndar: <https://ndar.nih.gov/api/datadictionary/v2/dataelement/>
prefix nfo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
prefix nidm: <http://purl.org/nidash/nidm#>
prefix niiri: <http://iri.nidash.org/>
prefix nlx: <http://uri.neuinfo.org/nif/nifstd/>
prefix obo: <http://purl.obolibrary.org/obo/>
prefix onli: <http://neurolog.unice.fr/ontoneurolog/v3.0/instrument.owl#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix pato: <http://purl.obolibrary.org/obo/pato#>
prefix performance_iq: <https://github.com/dbkeator/nidm-local-terms/issues/4>
prefix prov: <http://www.w3.org/ns/prov#>
prefix qc_anatomical_1: <https://github.com/dbkeator/nidm-local-terms/issues/63>
prefix qc_rest_1: <https://github.com/dbkeator/nidm-local-terms/issues/62>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix scr: <http://scicrunch.org/resolver/>
prefix sio: <http://semanticscience.org/ontology/sio.owl#>
prefix spm: <http://purl.org/nidash/spm#>
prefix vc: <http://www.w3.org/2006/vcard/ns#>
prefix verbal_iq: <https://github.com/dbkeator/nidm-local-terms/issues/3>
prefix xml: <http://www.w3.org/XML/1998/namespace>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>
prefix ilx: <http://uri.interlex.org/base/ilx_>

SELECT DISTINCT ?study ?ID ?Age ?Gender ?dx ?value ?tool ?structure
WHERE
{
   ?e a onli:assessment-instrument;
      prov:wasGeneratedBy ?act;
      ncicb:Age ?Age;
      ncit:Diagnosis ?dx;
      ndar:gender ?Gender;
      full4_iq: ?fiq;
      performance_iq: ?piq .

  ?act a onli:instrument-based-assessment;
    dct:isPartOf/dct:isPartOf [ a nidm:Project;
                                dctypes:title ?study];
    prov:wasAssociatedWith [ a prov:Person;
                             ndar:src_subject_id ?ID ] .

  ?tool_act a prov:Activity ;
          prov:qualifiedAssociation [prov:wasAssociatedWith [ndar:src_subject_id ?ID]],
                                    [prov:wasAssociatedWith [nidm:NIDM_0000164 ?tool]] .


  ?tool_stats prov:wasGeneratedBy ?tool_act;
            ?measure ?value .

  ?measure a measurement_datum:;
           rdfs:label ?label;
           isAbout: ?structure; #<http://purl.obolibrary.org/obo/UBERON_0001873>;
           hasMeasurementType: ilx:0112559;
           hasDatumType: ?datum_uri .

}

**Comment by satra** [comment]
@jbpoline - pushed a couple of changes. following the readme, i get about 58k records back.

**Comment by jbpoline** [comment]
@satra  : Not sure what was happening - I had a weird port error (port was already taken by a jupyer notebook) but I changed the port so not sure that was the issue. In any case, restarted blazegraph, made sure test.ttl seemed ok and got you 58k records back ... Back on track ! 
thanks a lot !

**Comment by satra** [comment]
@jbpoline - see the updated query. the reason hasUnit didn't work is because it wasn't in the prefix list

**Comment by jbpoline** [comment]
@satra (also @dbkeator )
thanks - I thought I had checked that !

I am adding laterality as well I suppose it refers to right or left side of the brain ? Does this PR https://github.com/satra/simple2_NIDM_examples/pull/1/commits makes sense ?

Also: do you know if "cerebral hemisphere" is the best proxy for "total brain volume" ? it seems that in the "structure" result I have limited options (see below) but may be missing something:
 
{'cavum septum pellucidum': '<http://purl.obolibrary.org/obo/UBERON_0001869>', 
'cerebellum': '<http://purl.obolibrary.org/obo/UBERON_0002285>', 
'cerebellar cortex': '<http://purl.obolibrary.org/obo/UBERON_0001954>', 
'perivascular space': '<http://purl.obolibrary.org/obo/UBERON_0001876>', 
"Ammon's horn": '<http://purl.obolibrary.org/obo/UBERON_0014930>', 
'inferior horn of the lateral ventricle': '<http://purl.obolibrary.org/obo/UBERON_0001874>', 
'brainstem': '<http://purl.obolibrary.org/obo/UBERON_0001886>', 
'amygdala': '<http://purl.obolibrary.org/obo/UBERON_0000959>', 
'optic chiasma': '<http://purl.obolibrary.org/obo/UBERON_0006091>', 
'dorsal plus ventral thalamus': '<http://purl.obolibrary.org/obo/UBERON_0002298>', 
'cerebral hemisphere': '<http://purl.obolibrary.org/obo/UBERON_0009857>', 
'caudate nucleus': '<http://purl.obolibrary.org/obo/UBERON_0002286>', 'telencephalic ventricle': '<http://purl.obolibrary.org/obo/UBERON_0002037>',
 'putamen': '<http://purl.obolibrary.org/obo/UBERON_0001873>',
 'third ventricle': '<http://purl.obolibrary.org/obo/UBERON_0006514>',
 'choroid plexus': '<http://purl.obolibrary.org/obo/UBERON_0002422>',
 'fourth ventricle': '<http://purl.obolibrary.org/obo/UBERON_0002129>',
 'pallidum': '<http://purl.obolibrary.org/obo/UBERON_0001897>', 
'nucleus accumbens': '<http://purl.obolibrary.org/obo/UBERON_0001882>'}

**Comment by satra** [comment]
@jbpoline - could you please change the target of the PR to the `wBrainVols` branch?

the mapping file is here: https://github.com/dbkeator/segstats_jsonld/blob/master/segstats_jsonld/mapping_data/freesurfermap.json

there are several things that could constitute brain vol - i would think this may be a good starting point: http://purl.obolibrary.org/obo/UBERON_0003128

**Comment by jbpoline** [comment]
@satra : PR is now on wBrainVols - thanks for pointing this
Atm the query does not return http://purl.obolibrary.org/obo/UBERON_0003128 - looking now how I can extend it
thanks again

**Pull request closed without merging**
